/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.hotel.apresentacao;

import br.com.hotel.dao.CategoriaDao;
import br.com.hotel.dao.ConnectionFactory;
import br.com.hotel.dao.ItemConsumoDao;
import br.com.hotel.modelo.Categoria;
import br.com.hotel.modelo.ItemConsumo;
import java.awt.Color;
import javax.swing.JOptionPane;
import teste.JpanelGerenciarHotel;

/**
 *
 * @author daylton
 */
public class TelaItensConsumo extends javax.swing.JFrame {
    private JpanelGerenciarHotel pnGerenciarHotel;
    /**
     * Creates new form TelaItensConsumo
     */
    public TelaItensConsumo() {
        initComponents();
        
        for(Categoria c: new CategoriaDao(new ConnectionFactory().getConnection()).listarCategorias()){
            cbCategoria.addItem(c);
        }
        
    }
    
    public TelaItensConsumo(javax.swing.JPanel form){
        this();
        pnGerenciarHotel = (JpanelGerenciarHotel) form;
    }
    
    public void preencherMsg(String s, Color c){
        lbMsg.setText(s);
        lbMsg.setForeground(c);               
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfDescricao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfValor = new javax.swing.JTextField();
        cbCategoria = new javax.swing.JComboBox();
        btnAdicionarCategoria = new javax.swing.JButton();
        btnRemoverCategoria = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        lbMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Itens de Consumo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Hotel Motel", 0, 36))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Hotel Oriental", 0, 24)); // NOI18N
        jLabel1.setText("Descrição");

        tfDescricao.setFont(new java.awt.Font("Hotel Oriental", 0, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Hotel Oriental", 0, 24)); // NOI18N
        jLabel2.setText("Valor");

        jLabel3.setFont(new java.awt.Font("Hotel Oriental", 0, 24)); // NOI18N
        jLabel3.setText("Categoria");

        tfValor.setFont(new java.awt.Font("Hotel Oriental", 0, 24)); // NOI18N

        cbCategoria.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        cbCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--------------" }));

        btnAdicionarCategoria.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        btnAdicionarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hotel/imagem/add.png"))); // NOI18N
        btnAdicionarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarCategoriaActionPerformed(evt);
            }
        });

        btnRemoverCategoria.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        btnRemoverCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hotel/imagem/delete.png"))); // NOI18N
        btnRemoverCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverCategoriaActionPerformed(evt);
            }
        });

        btnInserir.setFont(new java.awt.Font("Hotel Oriental", 0, 24)); // NOI18N
        btnInserir.setText("Inserir Item");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        lbMsg.setFont(new java.awt.Font("Hotel Oriental", 1, 18)); // NOI18N
        lbMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(tfDescricao))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdicionarCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoverCategoria)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionarCategoria)
                    .addComponent(btnRemoverCategoria)
                    .addComponent(jLabel2)
                    .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnInserir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        try{
            if(!"".equals(tfDescricao.getText())){
                if(!"".equals(tfValor.getText()) && Double.valueOf(tfValor.getText()) > 0){
                   if(cbCategoria.getSelectedIndex() > 0){
                       ItemConsumo ic = new ItemConsumo();
                       Categoria c = (Categoria) cbCategoria.getSelectedItem();
                       
                       ic.setDescricao(tfDescricao.getText());
                       ic.setValor(Double.valueOf(tfValor.getText()));
                       ic.setCategoriaId(c.getCategoriaId());
                       
                       ItemConsumoDao dao = new ItemConsumoDao(new ConnectionFactory().getConnection());
                       dao.inserirItemConsumo(ic);
                       
                       pnGerenciarHotel.preencherMsg("Item Adicionado", Color.green);
                       
                       this.dispose();
                   }else{
                        lbMsg.setText("Erro: Categoria Inválida!");
                        lbMsg.setForeground(Color.red);
                   }
                }else{
                    lbMsg.setText("Erro: Valor Inválido!");
                    lbMsg.setForeground(Color.red);
                }
            }else{
                lbMsg.setText("Erro: Descrição Inválida!");
                lbMsg.setForeground(Color.red);
            }
        }catch(Exception e){
            lbMsg.setText("Erro: " + e.getMessage());
            lbMsg.setForeground(Color.red);
        }
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAdicionarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarCategoriaActionPerformed
        TelaCategoria form1 = new TelaCategoria();
        form1.setAlwaysOnTop(true);
        form1.setVisible(true);
        form1.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnAdicionarCategoriaActionPerformed

    private void btnRemoverCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverCategoriaActionPerformed
        if(cbCategoria.getSelectedIndex()> 0){
            CategoriaDao dao = new CategoriaDao(new ConnectionFactory().getConnection());
            Categoria c = (Categoria) cbCategoria.getSelectedItem();
            
            int r = JOptionPane.showConfirmDialog(this, "Voce tem certeza disso?");
            
            if(r == 0){
                    dao.excluirCategoria(c.getCategoriaId());
                    preencherMsg("Categoria Excluida!", Color.red);
            }          
                        
        }else{
            preencherMsg("Categoria Invalida!", Color.red);
        }        
    }//GEN-LAST:event_btnRemoverCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaItensConsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaItensConsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaItensConsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaItensConsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaItensConsumo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarCategoria;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnRemoverCategoria;
    private javax.swing.JComboBox cbCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbMsg;
    private javax.swing.JTextField tfDescricao;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables
}
