/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.hotel.apresentacao;

import br.com.hotel.dao.AcomodacaoDao;
import br.com.hotel.dao.ConnectionFactory;
import br.com.hotel.dao.TipoAcomodacaoDao;
import br.com.hotel.modelo.Acomodacao;
import br.com.hotel.modelo.TipoAcomodacao;
import br.com.hotel.painel.PainelGerenciarHotel;
import java.awt.Color;

/**
 *
 * @author daylton
 */
public final class TelaAdicionarAcomodacao extends javax.swing.JFrame {
    
    /**
     * Creates new form TelaAdicionarAcomodacao
     */
    
    private PainelGerenciarHotel pnGerenciarHotel;
    
    public TelaAdicionarAcomodacao() {
        initComponents();    
        preencherComboTipoAcomodacao();
    }
        
    public TelaAdicionarAcomodacao(javax.swing.JPanel panel){
        this();
        pnGerenciarHotel = (PainelGerenciarHotel) panel;
        //preencherComboTipoAcomodacao();
    }
    
    public void preencherMsg(String s, Color c){
        lbMsg.setText(s);
        lbMsg.setForeground(c);
    }
    
    public void preencherComboTipoAcomodacao(){
        cbTipoAcomodacao.removeAllItems();
        cbTipoAcomodacao.addItem("-- Selecione --");
        for(TipoAcomodacao tpa: new TipoAcomodacaoDao(new ConnectionFactory().getConnection()).listarTipoAcomodacao()){
            cbTipoAcomodacao.addItem(tpa.getDescricao());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbTipoAcomodacao = new javax.swing.JComboBox<String>();
        jLabel2 = new javax.swing.JLabel();
        tfNumeroAcomodacao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfAndarAcomodacao = new javax.swing.JTextField();
        btnInserirAcomodacao = new javax.swing.JButton();
        lbMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        jLabel1.setText("Tipo de Acomodação");

        cbTipoAcomodacao.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        cbTipoAcomodacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- Selecione --" }));

        jLabel2.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        jLabel2.setText("Número da Acomodação");

        tfNumeroAcomodacao.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        jLabel3.setText("Andar da Acomodação");

        tfAndarAcomodacao.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N

        btnInserirAcomodacao.setFont(new java.awt.Font("Hotel Oriental", 0, 20)); // NOI18N
        btnInserirAcomodacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/hotel/imagem/add.png"))); // NOI18N
        btnInserirAcomodacao.setText("Adicionar Acomodação");
        btnInserirAcomodacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirAcomodacaoActionPerformed(evt);
            }
        });

        lbMsg.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        lbMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnInserirAcomodacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(cbTipoAcomodacao, 0, 316, Short.MAX_VALUE))
                            .addComponent(lbMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNumeroAcomodacao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAndarAcomodacao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbTipoAcomodacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNumeroAcomodacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tfAndarAcomodacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnInserirAcomodacao)
                .addGap(18, 18, 18)
                .addComponent(lbMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirAcomodacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirAcomodacaoActionPerformed
        String tipoAcomodacao = (String)cbTipoAcomodacao.getSelectedItem();
        TipoAcomodacaoDao tad = new TipoAcomodacaoDao(new ConnectionFactory().getConnection());
        TipoAcomodacao ta = tad.buscarTipoAcomodacao(tipoAcomodacao);
        if(ta.getDescricao() != null){
            if(!tfNumeroAcomodacao.getText().equals("") && Integer.valueOf(tfNumeroAcomodacao.getText()) > 0){
                if(!tfAndarAcomodacao.getText().equals("") && Integer.valueOf(tfAndarAcomodacao.getText()) > 0){
                    try{
                        Acomodacao a = new Acomodacao();
                        a.setNumAcomodacao(Integer.valueOf(tfNumeroAcomodacao.getText()));
                        a.setAndar(Integer.valueOf(tfAndarAcomodacao.getText()));
                        a.setReservado(false);
                        a.setTipoAcomodacaoId(ta.getTipoAcomodacaoId());
                        AcomodacaoDao ad = new AcomodacaoDao(new ConnectionFactory().getConnection());
                        int numeroAcomodacoesDisponiveis = ta.getQtdeAcomodacoes() - (ad.listarAcomodacoesPorTipo(ta.getTipoAcomodacaoId()).size());
                        if(numeroAcomodacoesDisponiveis > 0){
                            ad = new AcomodacaoDao(new ConnectionFactory().getConnection());
                            ad.inserirAcomodacao(a);   
                            pnGerenciarHotel.preecherTabelaAcomodacoes();
                            pnGerenciarHotel.preencherMsg("Acomodações do Tipo: " +  ta.getDescricao() + "adicionada. " + (numeroAcomodacoesDisponiveis - 1) + " acomodações disponiveis!", Color.GREEN);
                            this.dispose();
                        
                        }else{
                            preencherMsg("Número limite atingido para esse tipo de acomodação!", Color.RED);
                        }
                        
                        pnGerenciarHotel.preecherTabelaAcomodacoes();
                    }catch(Exception erro){
                        preencherMsg("Não foi possível adicionar acomodação!", Color.RED);
                    }
                }else{
                    preencherMsg("Numero do andar invalido!", Color.RED);
                }
            }else{
                preencherMsg("Numero da acomodação invalido!", Color.RED);
            }
        }else{
            preencherMsg("Você deve cadastrar um tipo de acomodação!", Color.RED);
        }
    }//GEN-LAST:event_btnInserirAcomodacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarAcomodacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarAcomodacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarAcomodacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarAcomodacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdicionarAcomodacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInserirAcomodacao;
    private javax.swing.JComboBox<String> cbTipoAcomodacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbMsg;
    private javax.swing.JTextField tfAndarAcomodacao;
    private javax.swing.JTextField tfNumeroAcomodacao;
    // End of variables declaration//GEN-END:variables
   
}
