/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.hotel.apresentacao;

import br.com.hotel.dao.AcomodacaoDao;
import br.com.hotel.dao.ConnectionFactory;
import br.com.hotel.dao.ConsumoDao;
import br.com.hotel.dao.ItemConsumoDao;
import br.com.hotel.dao.ReservaDao;
import br.com.hotel.dao.SaidaDao;
import br.com.hotel.dao.TipoPagamentoDao;
import br.com.hotel.modelo.Acomodacao;
import br.com.hotel.modelo.Consumo;
import br.com.hotel.modelo.ItemConsumo;
import br.com.hotel.modelo.Reserva;
import br.com.hotel.modelo.Saida;
import br.com.hotel.modelo.TipoPagamento;
import br.com.hotel.painel.PainelCadastroReservas;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

/**
 *
 * @author daylton
 */
public class TelaRegistrarSaida extends javax.swing.JFrame {

    /**
     * Creates new form TelaRegistrarSaida
     */
    private PainelCadastroReservas pnCadastroReservas;
    Reserva r;

    public TelaRegistrarSaida() {
        initComponents();
    }

    public TelaRegistrarSaida(Reserva reserva, javax.swing.JPanel panel) {
        this();
        pnCadastroReservas = (PainelCadastroReservas) panel;

        r = reserva;
        AcomodacaoDao ad = new AcomodacaoDao(new ConnectionFactory().getConnection());
        Acomodacao a = ad.buscarAcomodacao(r.getAcomodacaoId());
        ConsumoDao cd = new ConsumoDao(new ConnectionFactory().getConnection());
        ArrayList<Consumo> consumosDoQuarto = cd.listarConsumoPorAcomodacao(a.getNumAcomodacao());
        Date inicioEstadia = r.getDataChegada().getTime();
        Date fimEstadia = r.getDataSaida().getTime();
        ArrayList<Consumo> consumosHospede = new ArrayList<>();

        for (Consumo c : consumosDoQuarto) {
            Date dataConsumo = c.getDataConsumo();
            if ((dataConsumo.equals(inicioEstadia) || dataConsumo.equals(fimEstadia)) || (dataConsumo.after(inicioEstadia) && dataConsumo.before(fimEstadia))) {
                consumosHospede.add(c);
            }
        }

        double valorTotalItens = 0;

        for (Consumo c : consumosHospede) {
            ItemConsumoDao icd = new ItemConsumoDao(new ConnectionFactory().getConnection());
            ItemConsumo ic = icd.buscarItemConsumo(c.getItemId());
            valorTotalItens += (ic.getValor() * c.getQtdeConsumida());
        }

        tfNumeroDoQuartoSaida.setText(String.valueOf(a.getNumAcomodacao()));
        tfValorItensConsumidos.setText(String.valueOf(valorTotalItens));
        tfValorDiariaIndividualSaida.setText(String.valueOf(r.getValorDiaria()));
        tfDescontoTelaSaida.setText(String.valueOf(r.getDesconto()));
        
        preencherComboTipoPagamento();
    }

    public void preencherComboTipoPagamento() {
        TipoPagamentoDao tpd = new TipoPagamentoDao(new ConnectionFactory().getConnection());
        cbTipoPagamentos.removeAllItems();
        for (TipoPagamento tp : tpd.listarTiposPagamento()) {
            cbTipoPagamentos.addItem(tp.getTipo());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        tfNumeroDoQuartoSaida = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        dataSaidaTelaSaidas = new com.toedter.calendar.JDateChooser();
        jLabel23 = new javax.swing.JLabel();
        btnCalcularDiarias = new javax.swing.JButton();
        tfValorDiariasSaida = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tfValorDiariaIndividualSaida = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tfDescontoTelaSaida = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tfValorMultaSaida = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        tfValorItensConsumidos = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        cbTipoPagamentos = new javax.swing.JComboBox<String>();
        btnRegistrarSaida = new javax.swing.JButton();
        lblDias = new javax.swing.JLabel();
        lbMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar Saída Hospede", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Hotel Oriental", 0, 20))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        jLabel17.setText("Número Quarto");

        tfNumeroDoQuartoSaida.setEditable(false);
        tfNumeroDoQuartoSaida.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        tfNumeroDoQuartoSaida.setEnabled(false);

        jLabel18.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        jLabel18.setText("Data saída");

        jLabel23.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        jLabel23.setText("DIAS NO HOTEL");

        btnCalcularDiarias.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        btnCalcularDiarias.setText("Total Diárias");
        btnCalcularDiarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularDiariasActionPerformed(evt);
            }
        });

        tfValorDiariasSaida.setEditable(false);
        tfValorDiariasSaida.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        tfValorDiariasSaida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfValorDiariasSaida.setEnabled(false);

        jLabel19.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        jLabel19.setText("Valor da diária");

        tfValorDiariaIndividualSaida.setEditable(false);
        tfValorDiariaIndividualSaida.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        tfValorDiariaIndividualSaida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfValorDiariaIndividualSaida.setEnabled(false);

        jLabel20.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        jLabel20.setText("Desconto");

        tfDescontoTelaSaida.setEditable(false);
        tfDescontoTelaSaida.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        tfDescontoTelaSaida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfDescontoTelaSaida.setEnabled(false);

        jLabel22.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        jLabel22.setText("Multa por Sair antes do Término da Reserva");

        tfValorMultaSaida.setEditable(false);
        tfValorMultaSaida.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        tfValorMultaSaida.setEnabled(false);

        jLabel21.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        jLabel21.setText("Valor dos Itens Consumidos");

        tfValorItensConsumidos.setEditable(false);
        tfValorItensConsumidos.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        tfValorItensConsumidos.setEnabled(false);

        jLabel24.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        jLabel24.setText("Selecionar Tipo de Pagamento");

        cbTipoPagamentos.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        cbTipoPagamentos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        btnRegistrarSaida.setFont(new java.awt.Font("Hotel Oriental", 0, 20)); // NOI18N
        btnRegistrarSaida.setText("Registrar Saída do Hotel");
        btnRegistrarSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarSaidaActionPerformed(evt);
            }
        });

        lblDias.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        lblDias.setText("________");

        lbMsg.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        lbMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(tfNumeroDoQuartoSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDescontoTelaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfValorItensConsumidos, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCalcularDiarias, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfValorDiariasSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(lblDias)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfValorDiariaIndividualSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel24)
                            .addGap(18, 18, 18)
                            .addComponent(cbTipoPagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel22)
                            .addGap(18, 18, 18)
                            .addComponent(tfValorMultaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnRegistrarSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel18)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(dataSaidaTelaSaidas, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tfNumeroDoQuartoSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dataSaidaTelaSaidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel19)
                    .addComponent(tfValorDiariaIndividualSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDias, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcularDiarias)
                    .addComponent(tfValorDiariasSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tfValorItensConsumidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tfDescontoTelaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tfValorMultaSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(cbTipoPagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarSaida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularDiariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularDiariasActionPerformed
        Date inicioEstadia = r.getDataChegada().getTime();
        Date fimEstadia = r.getDataSaida().getTime();

        Calendar dataEscolhidaSaida = dataSaidaTelaSaidas.getCalendar();
        dataEscolhidaSaida.set(Calendar.HOUR_OF_DAY, 0);
        dataEscolhidaSaida.set(Calendar.MINUTE, 0);
        dataEscolhidaSaida.set(Calendar.MILLISECOND, 0);
        dataEscolhidaSaida.set(Calendar.SECOND, 0);
        Date dataSaida2 = dataEscolhidaSaida.getTime();
        if (!(dataSaida2.before(inicioEstadia) || dataSaida2.after(fimEstadia))) {
            long dias = (dataSaida2.getTime() - inicioEstadia.getTime()) / 86400000L;
            lblDias.setText(String.valueOf(dias));
            tfValorDiariasSaida.setText(String.valueOf(dias * r.getValorDiaria()));
            if (dataSaida2.before(fimEstadia)) {
                tfValorMultaSaida.setText(String.valueOf(r.getTaxaMulta()));
            } else {
                tfValorMultaSaida.setText("Sem multa.");
            }
        } else {
            lbMsg.setText("Data de Saída está fora do período da reserva.");
            lbMsg.setForeground(Color.red);
        }
    }//GEN-LAST:event_btnCalcularDiariasActionPerformed

    private void btnRegistrarSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarSaidaActionPerformed

        AcomodacaoDao ad = new AcomodacaoDao(new ConnectionFactory().getConnection());
        Acomodacao a = ad.buscarAcomodacao(r.getAcomodacaoId());
        ConsumoDao cd = new ConsumoDao(new ConnectionFactory().getConnection());
        ArrayList<Consumo> consumosDoQuarto = cd.listarConsumoPorAcomodacao(a.getNumAcomodacao());
        Date inicioEstadia = r.getDataChegada().getTime();
        Date fimEstadia = r.getDataSaida().getTime();
        ArrayList<Consumo> consumosHospede = new ArrayList<>();
        for (Consumo c : consumosDoQuarto) {
            Date dataConsumo = c.getDataConsumo();
            if ((dataConsumo.equals(inicioEstadia) || dataConsumo.equals(fimEstadia)) || (dataConsumo.after(inicioEstadia) && dataConsumo.before(fimEstadia))) {
                consumosHospede.add(c);
            }
        }
        double valorTotalItens = 0;

        for (Consumo c : consumosHospede) {
            ItemConsumoDao icd = new ItemConsumoDao(new ConnectionFactory().getConnection());
            ItemConsumo ic = icd.buscarItemConsumo(c.getItemId());
            valorTotalItens += (ic.getValor() * c.getQtdeConsumida());
        }

//            tfNumeroDoQuartoSaida.setText(String.valueOf(a.getNumAcomodacao()));
//            tfValorItensConsumidos.setText(String.valueOf(valorTotalItens));
//            tfValorDiariaIndividualSaida.setText(String.valueOf(r.getValorDiaria()));
//            tfDescontoTelaSaida.setText(String.valueOf(r.getDesconto()));
        Calendar dataEscolhidaSaida = dataSaidaTelaSaidas.getCalendar();
        dataEscolhidaSaida.set(Calendar.HOUR_OF_DAY, 0);
        dataEscolhidaSaida.set(Calendar.MINUTE, 0);
        dataEscolhidaSaida.set(Calendar.MILLISECOND, 0);
        dataEscolhidaSaida.set(Calendar.SECOND, 0);
        Date dataSaida2 = dataEscolhidaSaida.getTime();
        long dias = (dataSaida2.getTime() - inicioEstadia.getTime()) / 86400000L;
        SaidaDao sd = new SaidaDao(new ConnectionFactory().getConnection());
        Saida s = new Saida();
        s.setReservaId(r.getReservaId());
        s.setValorServicos(valorTotalItens);
        s.setNumAcomodacao(a.getNumAcomodacao());
        s.setNumDiarias((int) dias);
        s.setDesconto(r.getDesconto());
        s.setEstadiaPaga(true);
        GregorianCalendar gc = new GregorianCalendar();
        gc.setTime(dataSaida2);
        s.setDataSaida(gc);
        TipoPagamentoDao tpd = new TipoPagamentoDao(new ConnectionFactory().getConnection());
        TipoPagamento tp = tpd.buscarTipoPagamentoPorNome((String) cbTipoPagamentos.getSelectedItem());
        s.setTipoPagamentoId(tp.getTipoPagamentoId());
        sd.inserirSaida(s);

        ReservaDao rd = new ReservaDao(new ConnectionFactory().getConnection());
        rd.excluirReserva(r.getReservaId());
        pnCadastroReservas.preencherMsg("Saída do Hotel Concluida", Color.GREEN);
        pnCadastroReservas.preencherTabelaReservasSaida();

    }//GEN-LAST:event_btnRegistrarSaidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRegistrarSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRegistrarSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRegistrarSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRegistrarSaida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRegistrarSaida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularDiarias;
    private javax.swing.JButton btnRegistrarSaida;
    private javax.swing.JComboBox<String> cbTipoPagamentos;
    private com.toedter.calendar.JDateChooser dataSaidaTelaSaidas;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbMsg;
    private javax.swing.JLabel lblDias;
    private javax.swing.JTextField tfDescontoTelaSaida;
    private javax.swing.JTextField tfNumeroDoQuartoSaida;
    private javax.swing.JTextField tfValorDiariaIndividualSaida;
    private javax.swing.JTextField tfValorDiariasSaida;
    private javax.swing.JTextField tfValorItensConsumidos;
    private javax.swing.JTextField tfValorMultaSaida;
    // End of variables declaration//GEN-END:variables
}
