/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.hotel.apresentacao;

import br.com.hotel.dao.AcomodacaoDao;
import br.com.hotel.dao.AcompanhanteDao;
import br.com.hotel.dao.CartaoDao;
import br.com.hotel.dao.ConnectionFactory;
import br.com.hotel.dao.ReservaDao;
import br.com.hotel.dao.TipoAcomodacaoDao;
import br.com.hotel.modelo.TipoAcomodacao;
import br.com.hotel.modelo.Acomodacao;
import br.com.hotel.modelo.Acompanhante;
import br.com.hotel.modelo.Cartao;
import br.com.hotel.modelo.Hospede;
import br.com.hotel.modelo.Reserva;
import br.com.hotel.painel.PainelCadastroReservas;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author daylton
 */
public class TelaRegistrarReserva extends javax.swing.JFrame {

    /**
     * Creates new form TelaRegistrarReserva
     */
    
    private PainelCadastroReservas pnCadastroReserva;
    private Hospede h;
    private Cartao c;
    private Acomodacao acomodacaoEscolhida;
    private ArrayList<Acompanhante> acompanhantes;
    public int na;
    public int nc;
    
    public TelaRegistrarReserva() {
        initComponents();        
    }
    
    public TelaRegistrarReserva(Hospede hospede, javax.swing.JPanel panel){
        this();
        pnCadastroReserva = (PainelCadastroReservas) panel;    
        na = 1;
        nc = 0;
        this.acompanhantes = new ArrayList<>();
        this.c = new Cartao();
        
        h = hospede;
        
        lbNome.setText(h.getNome());
    }
    
    public void setValorDiaria(double valor){
        tfValorDiaria.setText(String.valueOf(valor));
    }
    
    public void setAcomodacao(Acomodacao acomodacaoEscolhida){
        this.acomodacaoEscolhida = acomodacaoEscolhida;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dataChegada = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        dataSaida = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        btnEscolherAcomodacao = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tfValorDiaria = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfMulta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfDesconto = new javax.swing.JTextField();
        btnAdicionarAcompanhante = new javax.swing.JButton();
        btnAdicionarDadosCartao = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lbMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        jLabel6.setText("Nome");

        lbNome.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        jLabel1.setText("Data Chegada");

        dataChegada.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        jLabel2.setText("Data Saída");

        dataSaida.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        jLabel3.setText("Selecionar Acomodação");

        btnEscolherAcomodacao.setFont(new java.awt.Font("Hotel Oriental", 0, 20)); // NOI18N
        btnEscolherAcomodacao.setText("Escolher");
        btnEscolherAcomodacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscolherAcomodacaoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        jLabel4.setText("Valor da Diária");

        tfValorDiaria.setEditable(false);
        tfValorDiaria.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        tfValorDiaria.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        jLabel5.setText("Taxa de Multa");

        tfMulta.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        jLabel7.setText("Desconto");

        tfDesconto.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N

        btnAdicionarAcompanhante.setFont(new java.awt.Font("Hotel Oriental", 0, 20)); // NOI18N
        btnAdicionarAcompanhante.setText("Adicionar Acompanhante");
        btnAdicionarAcompanhante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarAcompanhanteActionPerformed(evt);
            }
        });

        btnAdicionarDadosCartao.setFont(new java.awt.Font("Hotel Oriental", 0, 20)); // NOI18N
        btnAdicionarDadosCartao.setText("Adicionar Dados Cartão de Crédito");
        btnAdicionarDadosCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarDadosCartaoActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Hotel Oriental", 0, 20)); // NOI18N
        jButton2.setText("Realizar Reserva");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lbMsg.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        lbMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(lbNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dataSaida, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                    .addComponent(dataChegada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnAdicionarDadosCartao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAdicionarAcompanhante, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfValorDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnEscolherAcomodacao, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 12, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(dataChegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(dataSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnEscolherAcomodacao))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfValorDiaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAdicionarAcompanhante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdicionarDadosCartao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEscolherAcomodacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscolherAcomodacaoActionPerformed
        try{
            if(dataChegada.getDate()!= null && dataSaida.getDate()!= null){
                TelaSelecionarAcomodacao tsa = new TelaSelecionarAcomodacao(this, dataChegada.getDate(), dataSaida.getDate());
                tsa.setAlwaysOnTop(true);
                tsa.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            }else{
                lbMsg.setText("Data de chegada e saída devem ser escolhidas!");
                lbMsg.setForeground(Color.red);
            }
        }catch(Exception erro){
            lbMsg.setText("Data de chegada e saída devem ser escolhidas!");
            lbMsg.setForeground(Color.red);
        }
    }//GEN-LAST:event_btnEscolherAcomodacaoActionPerformed

    private void btnAdicionarAcompanhanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarAcompanhanteActionPerformed
        if(acomodacaoEscolhida!= null){
            TipoAcomodacaoDao tad = new TipoAcomodacaoDao(new ConnectionFactory().getConnection());
            TipoAcomodacao tipo = tad.buscarTipoAcomodacao(acomodacaoEscolhida.getTipoAcomodacaoId());
            TelaAdicionarAcompanhante taa = new TelaAdicionarAcompanhante(acompanhantes, tipo, this);
        }else{
            lbMsg.setText("Deve ser escolhida uma acomodação.");
            lbMsg.setForeground(Color.red);
        }
    }//GEN-LAST:event_btnAdicionarAcompanhanteActionPerformed

    private void btnAdicionarDadosCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarDadosCartaoActionPerformed
        if(this.h != null){
            TelaAdicionarCartao tac = new TelaAdicionarCartao(this.h, this.c);

        }else{
            lbMsg.setText("Nenhum hóspede foi selecionado!");
            lbMsg.setForeground(Color.red);
        }
    }//GEN-LAST:event_btnAdicionarDadosCartaoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            if(h!=null && acomodacaoEscolhida!= null && c!= null){
                Calendar chegada = dataChegada.getCalendar();
                Calendar saida = dataSaida.getCalendar();
                //System.out.println(chegada.getTime() + "    "+ saida.getTime());
                double diaria = Double.valueOf(tfValorDiaria.getText());
                double multa = Double.valueOf(tfMulta.getText());
                double desconto = Double.valueOf(tfDesconto.getText());

                CartaoDao cd = new CartaoDao(new ConnectionFactory().getConnection());
                cd.inserirCartao(c);
                cd = new CartaoDao(new ConnectionFactory().getConnection());
                Cartao c2 = cd.buscarCartoesPorNumero(c.getNumeroCartao());
                Reserva r = new Reserva();
                GregorianCalendar gc = new GregorianCalendar();
                gc.setTimeInMillis(chegada.getTimeInMillis());
                r.setDataChegada(gc);
                GregorianCalendar gc2 = new GregorianCalendar();
                gc2.setTimeInMillis(saida.getTimeInMillis());
                r.setDataSaida(gc2);
                r.setHospedeId(h.getHospedeId());
                r.setCartaoId(c2.getCartaoId());
                r.setDesconto(desconto);
                r.setTaxaMulta(multa);
                r.setValorDiaria(diaria);
                r.setAcomodacaoId(acomodacaoEscolhida.getAcomodacaoId());
                ReservaDao rd = new ReservaDao(new ConnectionFactory().getConnection());
                rd.inserirReserva(r);
                rd = new ReservaDao(new ConnectionFactory().getConnection());
                r = rd.buscarReservaPorHospede(h.getHospedeId());
                for(Acompanhante a : acompanhantes){
                    AcompanhanteDao ad = new AcompanhanteDao(new ConnectionFactory().getConnection());
                    a.setReservaId(r.getReservaId());
                    ad.inserirAcompanhante(a);
                }
                acomodacaoEscolhida.setReservado(true);
                AcomodacaoDao ad = new AcomodacaoDao(new ConnectionFactory().getConnection());
                ad.atualizarAcomodacao(acomodacaoEscolhida);
                JOptionPane.showMessageDialog(null, "Reserva Concluída!");
                this.h = null;
                this.acomodacaoEscolhida = null;
                this.c = new Cartao();
                this.na = 1;
                this.nc = 0;
                lbNome.setText("");
                pnCadastroReserva.preencherTabelaReservas();

            }else{
                JOptionPane.showMessageDialog(null, "Dados incompletos.");
            }

        }catch(Exception erro){
            JOptionPane.showMessageDialog(null, "Erro ao realizar reserva. Dados incompletos! \n Tente novamente.\n");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRegistrarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRegistrarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRegistrarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRegistrarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRegistrarReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarAcompanhante;
    private javax.swing.JButton btnAdicionarDadosCartao;
    private javax.swing.JButton btnEscolherAcomodacao;
    private com.toedter.calendar.JDateChooser dataChegada;
    private com.toedter.calendar.JDateChooser dataSaida;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbMsg;
    private javax.swing.JLabel lbNome;
    private javax.swing.JTextField tfDesconto;
    private javax.swing.JTextField tfMulta;
    private javax.swing.JTextField tfValorDiaria;
    // End of variables declaration//GEN-END:variables
}
