/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.hotel.apresentacao;

import br.com.hotel.modelo.Acompanhante;
import br.com.hotel.modelo.TipoAcomodacao;
import br.com.hotel.tabela.TableModelAcompanhantes;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;

/**
 *
 * @author guilherme
 */
public class TelaAdicionarAcompanhante extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdicionarAcompanhante
     */
    private TableModelAcompanhantes tma;
    private ArrayList<Acompanhante> acompanhantes;
    private TipoAcomodacao tipoAcomodacao;
    private TelaRegistrarReserva telaRegistrarReserva;
    private int numeroAdultos;
    private int numeroCriancas;
    
    
    public TelaAdicionarAcompanhante() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    public TelaAdicionarAcompanhante(ArrayList<Acompanhante> acompanhantes, TipoAcomodacao tipo, TelaRegistrarReserva trr){
        this();
        this.tipoAcomodacao = tipo;
        this.acompanhantes = acompanhantes;
        this.telaRegistrarReserva = trr;
        preencherTabelaAcompanhantes(acompanhantes);
        numeroAdultos = telaRegistrarReserva.na;
        numeroCriancas = telaRegistrarReserva.nc;
        lbNumAdultos.setText(String.valueOf(numeroAdultos));
        lbNumCriancas.setText(String.valueOf(numeroCriancas));
    }
    
    public void preencherTabelaAcompanhantes(ArrayList<Acompanhante> acompanhantes){
        tma = new TableModelAcompanhantes();
        tma.preencherLista(acompanhantes);
        tabelaAcompanhantes.setModel(tma);
        tabelaAcompanhantes.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabelaAcompanhantes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfNomeAcompanhante = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfIdadeAcompanhante = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAcompanhantes = new javax.swing.JTable();
        btnAdicionarAcompanhante = new javax.swing.JButton();
        btnExcluirAcompanhante = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbNumCriancas = new javax.swing.JLabel();
        lbNumAdultos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acompanhantes");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        jLabel1.setText("Nome do Acompanhante: ");

        tfNomeAcompanhante.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        jLabel2.setText("Idade do Acompanhante:");

        tfIdadeAcompanhante.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N

        tabelaAcompanhantes.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tabelaAcompanhantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaAcompanhantes);

        btnAdicionarAcompanhante.setFont(new java.awt.Font("Hotel Oriental", 0, 20)); // NOI18N
        btnAdicionarAcompanhante.setText("Adicionar");
        btnAdicionarAcompanhante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarAcompanhanteActionPerformed(evt);
            }
        });

        btnExcluirAcompanhante.setFont(new java.awt.Font("Hotel Oriental", 0, 18)); // NOI18N
        btnExcluirAcompanhante.setText("Excluir Acompanhante Selecionado");
        btnExcluirAcompanhante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirAcompanhanteActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Hotel Oriental", 1, 18)); // NOI18N
        jLabel3.setText("Crianças no Quarto:");

        jLabel4.setFont(new java.awt.Font("Hotel Oriental", 1, 18)); // NOI18N
        jLabel4.setText("Adultos no Quarto:");

        lbNumCriancas.setFont(new java.awt.Font("Hotel Oriental", 1, 24)); // NOI18N
        lbNumCriancas.setText("0");

        lbNumAdultos.setFont(new java.awt.Font("Hotel Oriental", 1, 24)); // NOI18N
        lbNumAdultos.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tfIdadeAcompanhante, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdicionarAcompanhante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNomeAcompanhante))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnExcluirAcompanhante, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lbNumCriancas)
                                    .addGap(65, 65, 65)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbNumAdultos)
                                .addGap(66, 66, 66)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNomeAcompanhante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfIdadeAcompanhante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionarAcompanhante))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbNumCriancas)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbNumAdultos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExcluirAcompanhante)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarAcompanhanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarAcompanhanteActionPerformed
        try{
            if(!"".equals(tfNomeAcompanhante.getText())){
                if(!"".equals(tfIdadeAcompanhante.getText())){
                    String nome = tfNomeAcompanhante.getText();
                    int idade = Integer.valueOf(tfIdadeAcompanhante.getText());
                    if(idade>18){
                        if(numeroAdultos<tipoAcomodacao.getNumAdultos()){
                            Acompanhante a = new Acompanhante();
                            a.setNome(nome);
                            a.setIdade(idade);
                            this.acompanhantes.add(a);
                            numeroAdultos++;
                            lbNumAdultos.setText(String.valueOf(numeroAdultos));
                            preencherTabelaAcompanhantes(acompanhantes);
                        }else{
                            JOptionPane.showMessageDialog(null, "Não é possível adicionar mais adultos.");
                        }
                    }else{
                        if(numeroCriancas<tipoAcomodacao.getNumCriancas()){
                            Acompanhante a = new Acompanhante();
                            a.setNome(nome);
                            a.setIdade(idade);
                            this.acompanhantes.add(a);
                            numeroCriancas++;
                            lbNumCriancas.setText(String.valueOf(numeroCriancas));
                            preencherTabelaAcompanhantes(acompanhantes);
                        }else{
                            JOptionPane.showMessageDialog(null, "Não é possível adicionar mais crianças.");
                        }
                    }
                    
                    telaRegistrarReserva.na = numeroAdultos;
                    telaRegistrarReserva.nc = numeroCriancas;
                }
            }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(null, "Erro ao adicionar acompanhante!");
        }
    }//GEN-LAST:event_btnAdicionarAcompanhanteActionPerformed

    private void btnExcluirAcompanhanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirAcompanhanteActionPerformed
        if(tabelaAcompanhantes.getSelectedRow() >= 0){
            Acompanhante a = tma.retornarObjetoSelecionado(tabelaAcompanhantes.getSelectedRow());
            
            this.acompanhantes.remove(a);
            if(a.getIdade() > 18){
                numeroAdultos--;
                telaRegistrarReserva.na = numeroAdultos;
                lbNumAdultos.setText(String.valueOf(numeroAdultos));
            }else{
                numeroCriancas--;
                telaRegistrarReserva.nc = numeroCriancas;
                lbNumCriancas.setText(String.valueOf(numeroCriancas));
            }
            JOptionPane.showMessageDialog(null, "Acompanhante: " + a.getNome() + "Excluído com sucesso");
            this.preencherTabelaAcompanhantes(acompanhantes);
        }else{
            JOptionPane.showMessageDialog(null, "Nenhum acompanhante selecionado.");
        }
    }//GEN-LAST:event_btnExcluirAcompanhanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarAcompanhante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarAcompanhante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarAcompanhante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionarAcompanhante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdicionarAcompanhante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarAcompanhante;
    private javax.swing.JButton btnExcluirAcompanhante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbNumAdultos;
    private javax.swing.JLabel lbNumCriancas;
    private javax.swing.JTable tabelaAcompanhantes;
    private javax.swing.JTextField tfIdadeAcompanhante;
    private javax.swing.JTextField tfNomeAcompanhante;
    // End of variables declaration//GEN-END:variables
}
