/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.hotel.apresentacao;

import br.com.hotel.dao.ConnectionFactory;
import br.com.hotel.dao.HospedeDao;
import br.com.hotel.modelo.Hospede;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author guilherme
 */
public class TesteCadastroHospedes extends javax.swing.JFrame {

    /**
     * Creates new form TesteCadastroHospedes
     */
    public TesteCadastroHospedes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfCpf = new javax.swing.JTextField();
        tfEndereco = new javax.swing.JTextField();
        tfTelefone = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        btnCadastro = new javax.swing.JButton();
        tfDataNascimento = new javax.swing.JFormattedTextField();
        btnListarHospedes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taArea = new javax.swing.JTextArea();
        btnAtualizar = new javax.swing.JButton();
        btnBuscarHospede = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome:");

        jLabel2.setText("CPF:");

        jLabel3.setText("Endereço:");

        jLabel4.setText("Telefone:");

        jLabel5.setText("Email:");

        jLabel6.setText("Data de Nascimento:");

        btnCadastro.setText("Cadastrar Hospede");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });

        try {
            tfDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnListarHospedes.setText("Listar Hospedes");
        btnListarHospedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarHospedesActionPerformed(evt);
            }
        });

        taArea.setEditable(false);
        taArea.setColumns(20);
        taArea.setRows(5);
        jScrollPane1.setViewportView(taArea);

        btnAtualizar.setText("Atualizar Hospede");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnBuscarHospede.setText("Buscar Hospede");
        btnBuscarHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarHospedeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfDataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfEndereco))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfNome)
                                    .addComponent(tfCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfTelefone)
                                    .addComponent(tfEmail)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnListarHospedes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscarHospede, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnListarHospedes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarHospede)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        try{
            if(!tfNome.getText().equals("")){
                if(!tfCpf.getText().equals("")){
                    if(!tfEndereco.getText().equals("")){
                        if(!tfEmail.getText().equals("")){
                            if(!tfTelefone.getText().equals("")){
                                if(!tfDataNascimento.getText().equals("")){
                                    String cpf = tfCpf.getText();
                                    String nome = tfNome.getText();
                                    String endereco = tfEndereco.getText();
                                    String email = tfEmail.getText();
                                    String telefone = tfTelefone.getText();
                                    String dataNascimento = tfDataNascimento.getText();
                                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                                    Date data = sdf.parse(dataNascimento);
                                    Hospede h = new Hospede();
                                    h.setCpf(cpf);
                                    h.setNome(nome);
                                    h.setEndereco(endereco);
                                    h.setEmail(email);
                                    h.setTelefone(telefone);
                                    h.setDataNascimento(data);
                                    HospedeDao hd = new HospedeDao(new ConnectionFactory().getConnection());
                                    hd.inserirHospede(h);
                                    JOptionPane.showMessageDialog(null, "Hospede Cadastrado");
                                }else{
                                    JOptionPane.showMessageDialog(null, "Erro: digite data");
                                }
                            }else{
                                JOptionPane.showMessageDialog(null, "Erro: digite telefone");
                            }
                        }else{
                            JOptionPane.showMessageDialog(null, "Erro: digite email");
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "Erro: digite endereço");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Erro: digite cpf");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Erro: digite nome");
            }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(null, "Erro: "  + erro.getMessage());
        }
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void btnListarHospedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarHospedesActionPerformed
        try{
            HospedeDao hd = new HospedeDao(new ConnectionFactory().getConnection());
            ArrayList<Hospede> hospedes = hd.listarHospedes();
            taArea.setText("");
            for(Hospede h: hospedes){
                taArea.append(h.getHospedeId() + " " + h.getNome() + " " + h.getCpf() + " " + h.getDataNascimento() + "\n");
            }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(null, "Erro: "  + erro.getMessage());
        }
    }//GEN-LAST:event_btnListarHospedesActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        try{
            String hospedeId  = JOptionPane.showInputDialog("Digite o id do Hospede: ");
            int id = Integer.valueOf(hospedeId);
            if(!tfNome.getText().equals("")){
                if(!tfCpf.getText().equals("")){
                    if(!tfEndereco.getText().equals("")){
                        if(!tfEmail.getText().equals("")){
                            if(!tfTelefone.getText().equals("")){
                                if(!tfDataNascimento.getText().equals("")){
                                    String cpf = tfCpf.getText();
                                    String nome = tfNome.getText();
                                    String endereco = tfEndereco.getText();
                                    String email = tfEmail.getText();
                                    String telefone = tfTelefone.getText();
                                    String dataNascimento = tfDataNascimento.getText();
                                    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                                    Date data = sdf.parse(dataNascimento);
                                    HospedeDao hd = new HospedeDao(new ConnectionFactory().getConnection());
                                    Hospede h = hd.buscarHospede(id);
                                    h.setCpf(cpf);
                                    h.setNome(nome);
                                    h.setEndereco(endereco);
                                    h.setEmail(email);
                                    h.setTelefone(telefone);
                                    h.setDataNascimento(data);
                                    HospedeDao hd2 = new HospedeDao(new ConnectionFactory().getConnection());
                                    hd2.atualizarHospede(h);
                                    JOptionPane.showMessageDialog(null, "Hospede Atualizado!");
                                }else{
                                    JOptionPane.showMessageDialog(null, "Erro: digite data");
                                }
                            }else{
                                JOptionPane.showMessageDialog(null, "Erro: digite telefone");
                            }
                        }else{
                            JOptionPane.showMessageDialog(null, "Erro: digite email");
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "Erro: digite endereço");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Erro: digite cpf");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Erro: digite nome");
            }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(null, "Erro: "  + erro.getMessage());
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnBuscarHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarHospedeActionPerformed
        try{
            String hospedeId  = JOptionPane.showInputDialog("Digite o id do Hospede: ");
            int id = Integer.valueOf(hospedeId);
            HospedeDao hd = new HospedeDao(new ConnectionFactory().getConnection());
            Hospede h = hd.buscarHospede(id);
            tfNome.setText(h.getNome());
            tfCpf.setText(h.getCpf());
            tfEndereco.setText(h.getEndereco());
            tfEmail.setText(h.getEmail());
            tfTelefone.setText(h.getTelefone());
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            tfDataNascimento.setText(sdf.format(h.getDataNascimento()));
            JOptionPane.showMessageDialog(null, "Hospede encontrado!");
        }catch(Exception erro){
            JOptionPane.showMessageDialog(null, "Erro: "  + erro.getMessage());
        }
    }//GEN-LAST:event_btnBuscarHospedeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TesteCadastroHospedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TesteCadastroHospedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TesteCadastroHospedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TesteCadastroHospedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TesteCadastroHospedes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnBuscarHospede;
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnListarHospedes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taArea;
    private javax.swing.JTextField tfCpf;
    private javax.swing.JFormattedTextField tfDataNascimento;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfTelefone;
    // End of variables declaration//GEN-END:variables
}
